import { PRIVACY_CLIENT_SIDE, PRIVACY_SERVER_SIDE } from "./shared";

const docRelated = [
  { href: "/doc-to-pdf", label: "Doc to PDF" },
  { href: "/pdf-to-doc", label: "PDF to DOCX" },
  { href: "/merge-pdf", label: "Merge PDF" },
  { href: "/split-pdf", label: "Split PDF" },
  { href: "/compress-pdf", label: "Compress PDF" },
];

export const documentToolsSeo = {
  "doc-to-pdf": {
    id: "doc-to-pdf",
    path: "/doc-to-pdf",
    title: "DOC to PDF Converter – Word to PDF Free Online",
    description: "Convert Word DOC and DOCX files to PDF online. Preserve layout and fonts. Free document converter on ConvertMastery.",
    h1: "DOC to PDF Converter",
    intro: "Convert Word documents to universally readable PDF files. Ideal for sharing contracts, resumes, and reports that must look the same on every device.",
    howToUse: ["Upload a .doc or .docx file.", "Click Convert.", "Download your PDF."],
    supportedFormats: "Input: DOC, DOCX. Output: PDF.",
    privacySecurity: PRIVACY_SERVER_SIDE,
    useCases: ["Share resumes as PDF.", "Submit assignments in required PDF format.", "Archive Word files in a fixed layout."],
    relatedTools: docRelated.filter((t) => t.href !== "/doc-to-pdf"),
    faqs: [
      { q: "Will formatting be preserved?", a: "We aim to preserve layout, fonts, and images. Complex documents should be reviewed after conversion." },
      { q: "Is DOCX supported?", a: "Yes, both .doc and .docx are supported." },
    ],
  },
  "pdf-to-doc": {
    id: "pdf-to-doc",
    path: "/pdf-to-doc",
    title: "PDF to DOCX Converter – PDF to Word Free",
    description: "Convert PDF to editable Word DOCX or TXT online. Extract and edit PDF content. Free on ConvertMastery.",
    h1: "PDF to DOCX Converter",
    intro: "Turn static PDFs into editable Word documents. Useful when you need to update text, reuse content, or collaborate in Microsoft Word or Google Docs.",
    howToUse: ["Upload your PDF.", "Choose DOCX or TXT output.", "Download the converted file."],
    supportedFormats: "Input: PDF. Output: DOCX, TXT.",
    privacySecurity: PRIVACY_SERVER_SIDE,
    useCases: ["Edit an old PDF report.", "Reuse PDF content in a new document.", "Extract plain text from a PDF."],
    relatedTools: docRelated.filter((t) => t.href !== "/pdf-to-doc"),
    faqs: [
      { q: "Can I convert scanned PDFs?", a: "Scanned image-only PDFs may need OCR first. Try Extract Text (OCR) for image-based pages." },
    ],
  },
  "merge-pdf": {
    id: "merge-pdf",
    path: "/merge-pdf",
    title: "Merge PDF Online – Combine PDF Files Free",
    description: "Merge multiple PDF files into one document online. Drag to reorder pages. Free PDF merger on ConvertMastery.",
    h1: "Merge PDF Files Online",
    intro: "Combine invoices, chapters, scans, and reports into a single PDF. Reorder files before merging and download instantly.",
    howToUse: ["Upload two or more PDF files.", "Drag to set merge order.", "Click Merge and download."],
    supportedFormats: "Input: PDF. Output: single merged PDF.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Combine monthly statements.", "Merge scanned pages into one file.", "Build a portfolio PDF from multiple sources."],
    relatedTools: docRelated.filter((t) => t.href !== "/merge-pdf"),
    faqs: [
      { q: "How many PDFs can I merge?", a: "Multiple files are supported; very large batches depend on browser memory." },
      { q: "Can I reorder before merging?", a: "Yes. Drag files to change order." },
    ],
  },
  "split-pdf": {
    id: "split-pdf",
    path: "/split-pdf",
    title: "Split PDF Online – Extract PDF Pages Free",
    description: "Split PDF into separate files or extract specific pages. Free online PDF splitter on ConvertMastery.",
    h1: "Split PDF Online",
    intro: "Extract individual pages or split a large PDF into smaller files. Perfect for sharing only the pages you need.",
    howToUse: ["Upload a PDF.", "Select pages or ranges to extract.", "Download split files or a ZIP."],
    supportedFormats: "Input: PDF. Output: PDF (one or more files).",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Extract one chapter from a manual.", "Separate a signed page from a contract.", "Split a bulk scan into individual documents."],
    relatedTools: docRelated.filter((t) => t.href !== "/split-pdf"),
    faqs: [
      { q: "Can I extract a page range?", a: "Yes. Specify ranges or select individual pages." },
    ],
  },
  "compress-pdf": {
    id: "compress-pdf",
    path: "/compress-pdf",
    title: "Compress PDF Online – Reduce PDF File Size Free",
    description: "Compress PDF files to reduce size for email and uploads. Free PDF compressor on ConvertMastery.",
    h1: "Compress PDF Online",
    intro: "Shrink PDF file size without unnecessary quality loss. Great for email attachments, web uploads, and storage savings.",
    howToUse: ["Upload your PDF.", "Choose compression level.", "Download the smaller PDF."],
    supportedFormats: "Input: PDF. Output: compressed PDF.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Email large PDF reports.", "Meet portal upload size limits.", "Reduce storage for archived documents."],
    relatedTools: docRelated.filter((t) => t.href !== "/compress-pdf"),
    faqs: [
      { q: "How much smaller will my PDF get?", a: "Results depend on original content. Image-heavy PDFs compress more than text-only files." },
    ],
  },
  "pdf-unlock-protect": {
    id: "pdf-unlock-protect",
    path: "/pdf-unlock-protect",
    title: "PDF Unlock & Protect – Add or Remove PDF Password",
    description: "Unlock password-protected PDFs or add password protection online. Free PDF security tool on ConvertMastery.",
    h1: "PDF Unlock & Protect",
    intro: "Remove passwords from PDFs you own or add encryption to sensitive documents. Use only on files you have legal rights to modify.",
    howToUse: ["Upload a PDF.", "Choose unlock or protect mode.", "Enter password if required.", "Download the result."],
    supportedFormats: "PDF with optional password protection.",
    privacySecurity: PRIVACY_SERVER_SIDE,
    useCases: ["Open a PDF you forgot the password for (that you own).", "Protect confidential contracts.", "Restrict printing or copying on shared PDFs."],
    relatedTools: docRelated,
    faqs: [
      { q: "Can I unlock any PDF?", a: "Only PDFs you legally own or have permission to unlock. We do not support bypassing unauthorized protection." },
    ],
  },
  scanner: {
    id: "scanner",
    path: "/scanner",
    title: "Document Scanner Online – Scan to PDF Free",
    description: "Scan documents with your camera or upload images. Create clean PDF scans online. Free on ConvertMastery.",
    h1: "Online Document Scanner",
    intro: "Turn phone photos and uploads into crisp scanned PDFs. Auto-crop, enhance contrast, and export multi-page documents.",
    howToUse: ["Use your camera or upload images.", "Adjust crop and enhancement.", "Export as PDF."],
    supportedFormats: "Camera capture, JPG, PNG. Output: PDF.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Scan receipts on the go.", "Digitize signed forms.", "Create PDFs from whiteboard photos."],
    relatedTools: [
      { href: "/image-to-pdf", label: "Image to PDF" },
      { href: "/extract-text", label: "Extract Text (OCR)" },
    ],
    faqs: [
      { q: "Do I need a physical scanner?", a: "No. Your phone camera or existing photos work." },
    ],
  },
  "grammer-checker": {
    id: "grammer-checker",
    path: "/grammer-checker",
    title: "Free Grammar Checker Online",
    description: "Check grammar, spelling, and clarity in your writing. Free online grammar checker on ConvertMastery.",
    h1: "Free Grammar Checker",
    intro: "Improve emails, essays, and professional writing with instant grammar and spelling suggestions.",
    howToUse: ["Paste or type your text.", "Review highlighted issues.", "Apply suggestions and copy corrected text."],
    supportedFormats: "Plain text input.",
    privacySecurity: "Text is processed to provide suggestions. Do not paste highly sensitive credentials or personal data.",
    useCases: ["Polish business emails.", "Review blog drafts.", "Check academic assignments."],
    relatedTools: [{ href: "/resume-builder", label: "Resume Builder" }],
    faqs: [
      { q: "Is the grammar checker free?", a: "Yes for standard use on ConvertMastery." },
    ],
  },
};
