import { PRIVACY_CLIENT_SIDE } from "./shared";

export const videoToolsSeo = {
  "video-convert": {
    id: "video-convert",
    path: "/video-convert",
    title: "Free Video Converter Online – MP4, WebM, MOV",
    description: "Convert video formats online. MP4, WebM, MOV, and more. Browser-based video converter on ConvertMastery.",
    h1: "Free Online Video Converter",
    intro: "Convert videos between popular formats without desktop software. Adjust resolution and codec settings for web, mobile, or archive use.",
    howToUse: ["Upload a video file.", "Select output format and settings.", "Convert and download."],
    supportedFormats: "MP4, WebM, MOV, AVI, MKV, and more.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Convert MOV to MP4 for wider compatibility.", "Prepare videos for web embedding.", "Reduce resolution for mobile sharing."],
    relatedTools: [{ href: "/video-compress", label: "Video Compressor" }, { href: "/video-trim", label: "Video Trimmer" }],
    faqs: [
      { q: "Is video conversion done in the browser?", a: "Yes, using WebAssembly FFmpeg in your browser." },
    ],
  },
  "video-compress": {
    id: "video-compress",
    path: "/video-compress",
    title: "Video Compressor Online – Reduce Video File Size",
    description: "Compress videos online to reduce file size. Free video compressor on ConvertMastery.",
    h1: "Video Compressor Online",
    intro: "Shrink video files for email, messaging apps, and websites while keeping acceptable quality.",
    howToUse: ["Upload a video.", "Choose compression preset or target size.", "Download compressed video."],
    supportedFormats: "MP4, WebM, MOV, and common formats.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Send videos under email size limits.", "Optimize clips for social media.", "Save storage on archived footage."],
    relatedTools: [{ href: "/video-convert", label: "Video Converter" }, { href: "/video-trim", label: "Video Trimmer" }],
    faqs: [],
  },
  "video-trim": {
    id: "video-trim",
    path: "/video-trim",
    title: "Video Trimmer Online – Cut Video Clips Free",
    description: "Trim and cut video clips online. Set start and end points. Free video trimmer on ConvertMastery.",
    h1: "Video Trimmer Online",
    intro: "Cut unwanted sections from videos and export a shorter clip. Perfect for highlights, demos, and social clips.",
    howToUse: ["Upload a video.", "Set trim start and end points.", "Export the trimmed clip."],
    supportedFormats: "MP4, WebM, MOV.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Create short social clips.", "Remove dead air from recordings.", "Extract a segment from a longer video."],
    relatedTools: [{ href: "/video-convert", label: "Video Converter" }, { href: "/video-compress", label: "Video Compressor" }],
    faqs: [],
  },
};

export const audioToolsSeo = {
  "audio-convert": {
    id: "audio-convert",
    path: "/audio-convert",
    title: "Audio Converter Online – MP3, WAV, OGG",
    description: "Convert audio files between MP3, WAV, OGG, and more. Free online audio converter on ConvertMastery.",
    h1: "Audio Converter Online",
    intro: "Change audio formats for players, editors, and podcasts. Batch convert tracks with quality control.",
    howToUse: ["Upload audio files.", "Select output format.", "Convert and download."],
    supportedFormats: "MP3, WAV, OGG, FLAC, AAC, M4A.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Convert WAV to MP3 for smaller files.", "Prepare audio for video projects.", "Normalize formats for a music library."],
    relatedTools: [{ href: "/text-to-speech", label: "Text to Speech" }, { href: "/speech-to-text", label: "Speech to Text" }],
    faqs: [],
  },
  "text-to-speech": {
    id: "text-to-speech",
    path: "/text-to-speech",
    title: "Text to Speech Online – Free TTS",
    description: "Convert text to natural speech audio. Free text-to-speech tool on ConvertMastery.",
    h1: "Text to Speech",
    intro: "Generate spoken audio from written text for accessibility, voiceovers, and learning materials.",
    howToUse: ["Enter or paste text.", "Select voice and speed.", "Generate and download audio."],
    supportedFormats: "Text input. Output: MP3 or WAV.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Accessibility for visually impaired users.", "Draft podcast narration.", "Language learning pronunciation."],
    relatedTools: [{ href: "/speech-to-text", label: "Speech to Text" }, { href: "/audio-convert", label: "Audio Converter" }],
    faqs: [],
  },
  "speech-to-text": {
    id: "speech-to-text",
    path: "/speech-to-text",
    title: "Speech to Text – Free Audio Transcription",
    description: "Transcribe audio to text online. Free speech-to-text on ConvertMastery.",
    h1: "Speech to Text",
    intro: "Turn voice recordings into editable text for meeting notes, captions, and documentation.",
    howToUse: ["Upload an audio file or record.", "Run transcription.", "Copy or download text."],
    supportedFormats: "MP3, WAV, M4A, and microphone input.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Transcribe interviews.", "Create meeting minutes.", "Generate video captions."],
    relatedTools: [{ href: "/text-to-speech", label: "Text to Speech" }, { href: "/extract-text", label: "Extract Text (OCR)" }],
    faqs: [],
  },
};

export const utilityToolsSeo = {
  "qr-barcode": {
    id: "qr-barcode",
    path: "/qr-barcode",
    title: "QR Code & Barcode Generator – Free Online",
    description: "Create QR codes and barcodes for URLs, text, and products. Free generator on ConvertMastery.",
    h1: "QR Code & Barcode Generator",
    intro: "Generate scannable QR codes for websites, Wi-Fi, contact cards, and plain text. Create standard barcodes for inventory and retail.",
    howToUse: ["Choose QR or barcode type.", "Enter content (URL, text, etc.).", "Customize size and download PNG/SVG."],
    supportedFormats: "QR codes, Code 128, EAN, UPC barcodes.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Restaurant menu QR codes.", "Event check-in links.", "Product SKU barcodes."],
    relatedTools: [{ href: "/url-shortener", label: "URL Shortener" }],
    faqs: [
      { q: "Are QR codes free for commercial use?", a: "Yes. Generated codes are yours to use." },
    ],
  },
  "url-shortener": {
    id: "url-shortener",
    path: "/url-shortener",
    title: "URL Shortener – Short Links Free",
    description: "Create short URLs for sharing. Free URL shortener on ConvertMastery.",
    h1: "URL Shortener",
    intro: "Turn long URLs into short, shareable links for social media, SMS, and print materials.",
    howToUse: ["Paste a long URL.", "Generate short link.", "Copy and share."],
    supportedFormats: "HTTP/HTTPS URLs.",
    privacySecurity: "Short links redirect through our service. Do not shorten links to phishing or malicious content.",
    useCases: ["Share links on Twitter/X.", "Trackable marketing campaigns.", "Cleaner links in presentations."],
    relatedTools: [{ href: "/qr-barcode", label: "QR Code Generator" }],
    faqs: [],
  },
  "file-to-zip": {
    id: "file-to-zip",
    path: "/file-to-zip",
    title: "File to ZIP – Compress Files Online",
    description: "Create ZIP archives from multiple files online. Free file zipper on ConvertMastery.",
    h1: "File to ZIP Converter",
    intro: "Bundle multiple files into a single ZIP archive for easier sharing and download.",
    howToUse: ["Upload files.", "Create ZIP archive.", "Download."],
    supportedFormats: "Any file types into ZIP.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Package documents for email.", "Bundle project assets.", "Compress folders for upload."],
    relatedTools: [{ href: "/merge-pdf", label: "Merge PDF" }],
    faqs: [],
  },
  calculators: {
    id: "calculators",
    path: "/calculators",
    title: "Online Calculators & Unit Converters",
    description: "Free calculators and unit converters. BMI, percentage, length, weight, and more on ConvertMastery.",
    h1: "Calculators & Converters",
    intro: "Quick everyday calculations and unit conversions in one place. No app install required.",
    howToUse: ["Select a calculator or converter.", "Enter values.", "View instant results."],
    supportedFormats: "Various numeric inputs.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Unit conversion for recipes and travel.", "Percentage and tip calculations.", "BMI and health estimates."],
    relatedTools: [{ href: "/distance-calculator", label: "Distance Calculator" }],
    faqs: [],
  },
  "resume-builder": {
    id: "resume-builder",
    path: "/resume-builder",
    title: "Free Resume / CV Builder Online",
    description: "Build a professional resume or CV online. Free resume builder on ConvertMastery.",
    h1: "Resume & CV Builder",
    intro: "Create a polished resume with sections for experience, education, and skills. Preview and export when ready.",
    howToUse: ["Fill in personal and work details.", "Preview layout.", "Export or print."],
    supportedFormats: "Resume export to PDF.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Job applications.", "Career updates.", "Student internship resumes."],
    relatedTools: [{ href: "/grammer-checker", label: "Grammar Checker" }, { href: "/doc-to-pdf", label: "Doc to PDF" }],
    faqs: [],
  },
  "color-picker": {
    id: "color-picker",
    path: "/color-picker",
    title: "Color Picker – HEX, RGB, HSL Converter Free",
    description: "Online color picker and converter. Convert HEX, RGB, and HSL with live preview. Free on ConvertMastery.",
    h1: "Color Picker & Converter",
    intro: "Pick any color and get HEX, RGB, and HSL values ready for CSS. Perfect for designers, students, and front-end developers.",
    howToUse: ["Use the color picker or type a HEX value.", "Adjust RGB or HSL.", "Copy the format you need."],
    supportedFormats: "HEX, RGB, HSL.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Match brand colors for a website.", "Convert design tokens between formats.", "Explore palettes for school projects."],
    relatedTools: [
      { href: "/favicon-generator", label: "Favicon Generator" },
      { href: "/qr-barcode", label: "QR & Barcode" },
    ],
    faqs: [
      { q: "Does it work offline after load?", a: "Yes. Conversion is fully client-side." },
    ],
  },
  "json-formatter": {
    id: "json-formatter",
    path: "/json-formatter",
    title: "JSON Formatter & Validator – Free Online",
    description: "Format, validate, and minify JSON online. Free JSON beautifier that runs in your browser on ConvertMastery.",
    h1: "JSON Formatter & Validator",
    intro: "Paste messy JSON to beautify, validate, or minify it instantly. Ideal for APIs, config files, and debugging payloads—without uploading data.",
    howToUse: ["Paste JSON.", "Click Format or Minify.", "Copy the result."],
    supportedFormats: "JSON text.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Pretty-print API responses.", "Validate config before deploy.", "Minify JSON for payloads."],
    relatedTools: [
      { href: "/base64-converter", label: "Base64 Encode/Decode" },
      { href: "/hash-generator", label: "Hash Generator" },
    ],
    faqs: [
      { q: "Is my JSON uploaded?", a: "No. Parsing happens entirely in your browser." },
    ],
  },
  "base64-converter": {
    id: "base64-converter",
    path: "/base64-converter",
    title: "Base64 Encode / Decode – Text & Image Free",
    description: "Encode text or images to Base64 and decode Base64 online. Free client-side Base64 tool on ConvertMastery.",
    h1: "Base64 Encode / Decode",
    intro: "Convert text and images to Base64 strings, or decode Base64 back to readable text and image previews. Useful for data URIs, email embeds, and debugging.",
    howToUse: ["Choose Encode or Decode.", "Paste text or upload an image.", "Copy the output."],
    supportedFormats: "UTF-8 text and common image formats.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Create CSS/HTML data URIs.", "Debug encoded API fields.", "Embed small images without hosting."],
    relatedTools: [
      { href: "/json-formatter", label: "JSON Formatter" },
      { href: "/hash-generator", label: "Hash Generator" },
    ],
    faqs: [],
  },
  "distance-calculator": {
    id: "distance-calculator",
    path: "/distance-calculator",
    title: "Distance Calculator – Measure Between Points",
    description: "Calculate distance between two locations. Free distance calculator on ConvertMastery.",
    h1: "Distance Calculator",
    intro: "Measure straight-line or route distance between addresses or coordinates for planning and logistics.",
    howToUse: ["Enter two locations.", "View distance in km or miles."],
    supportedFormats: "Addresses and coordinates.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Delivery radius planning.", "Travel distance estimates.", "Fitness route planning."],
    relatedTools: [{ href: "/radius-map", label: "Radius Map" }, { href: "/coordinates-finder", label: "Coordinates Finder" }],
    faqs: [],
  },
};

export const mapsToolsSeo = {
  "radius-map": {
    id: "radius-map",
    path: "/radius-map",
    title: "Radius Map Tool – Draw Circle on Map",
    description: "Draw a radius circle on a map for delivery zones and coverage areas. Free on ConvertMastery.",
    h1: "Radius Map Tool",
    intro: "Visualize a circular coverage area on an interactive map. Set center point and radius in km or miles.",
    howToUse: ["Click map to set center.", "Enter radius.", "View and share the coverage circle."],
    supportedFormats: "Map coordinates, km/miles radius.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Delivery zone planning.", "Store coverage analysis.", "Event influence areas."],
    relatedTools: [{ href: "/embed-map-generator", label: "Embed Map Generator" }, { href: "/coordinates-finder", label: "Coordinates Finder" }],
    faqs: [],
  },
  "coordinates-finder": {
    id: "coordinates-finder",
    path: "/coordinates-finder",
    title: "Coordinates Finder – Get Lat Long from Map",
    description: "Find latitude and longitude by clicking on a map. Free coordinates finder on ConvertMastery.",
    h1: "Coordinates Finder",
    intro: "Click anywhere on a map to get precise latitude and longitude coordinates for GIS, hiking, and development.",
    howToUse: ["Click on the map.", "Copy lat/long coordinates."],
    supportedFormats: "Decimal degrees (lat, lng).",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["GIS data collection.", "Geocaching waypoints.", "Web development map testing."],
    relatedTools: [{ href: "/address-to-latlong", label: "Address to Lat Long" }],
    faqs: [],
  },
  "address-to-latlong": {
    id: "address-to-latlong",
    path: "/address-to-latlong",
    title: "Address to Latitude Longitude Converter",
    description: "Convert addresses to GPS coordinates. Free geocoding tool on ConvertMastery.",
    h1: "Address to Lat Long Converter",
    intro: "Turn street addresses into latitude and longitude for maps, APIs, and logistics systems.",
    howToUse: ["Enter an address.", "View coordinates on the map.", "Copy lat/long."],
    supportedFormats: "Street addresses worldwide.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Populate map markers.", "Shipping coordinate lookup.", "Real estate location data."],
    relatedTools: [{ href: "/coordinates-finder", label: "Coordinates Finder" }],
    faqs: [],
  },
  "embed-map-generator": {
    id: "embed-map-generator",
    path: "/embed-map-generator",
    title: "Embed Map Generator – iframe Map Code",
    description: "Generate embeddable map iframe code for your website. Free on ConvertMastery.",
    h1: "Embed Map Generator",
    intro: "Create customizable map embeds with markers and zoom for blogs, landing pages, and contact pages.",
    howToUse: ["Set location and zoom.", "Customize marker.", "Copy embed HTML code."],
    supportedFormats: "HTML iframe embed code.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Contact page maps.", "Event venue embeds.", "Store locator widgets."],
    relatedTools: [{ href: "/radius-map", label: "Radius Map" }],
    faqs: [],
  },
};
