import { PRIVACY_CLIENT_SIDE, PRIVACY_SERVER_SIDE, SECURITY_TOOL_DISCLAIMER, ADSENSE_DISCLAIMER } from "./shared";

const securityRelated = [
  { href: "/password-generator", label: "Password Generator" },
  { href: "/password-strength-checker", label: "Password Strength Checker" },
  { href: "/data-breach-checker", label: "Data Breach Checker" },
  { href: "/whois-checker", label: "Whois Checker" },
  { href: "/metadata-remover", label: "Metadata Remover" },
];

export const securityToolsSeo = {
  "password-generator": {
    id: "password-generator",
    path: "/password-generator",
    title: "Secure Password Generator – Strong Random Passwords",
    description: "Generate strong, random passwords with custom length and character sets. Free secure password generator on ConvertMastery.",
    h1: "Secure Password Generator",
    intro: "Create cryptographically random passwords that resist brute-force and dictionary attacks. Customize length, symbols, and exclusions for your policy requirements.",
    howToUse: ["Set password length and character options.", "Click Generate.", "Copy the password to your password manager."],
    supportedFormats: "Customizable character sets and length up to 128 characters.",
    privacySecurity: "Passwords are generated locally in your browser using crypto.getRandomValues(). We never store or transmit generated passwords.",
    useCases: ["New account registrations.", "Rotate compromised passwords.", "Generate API keys and tokens."],
    relatedTools: securityRelated.filter((t) => t.href !== "/password-generator"),
    faqs: [
      { q: "Are generated passwords stored?", a: "No. Generation happens entirely in your browser." },
      { q: "How long should my password be?", a: "We recommend at least 16 characters with mixed character types." },
    ],
  },
  "password-strength-checker": {
    id: "password-strength-checker",
    path: "/password-strength-checker",
    title: "Password Strength Checker – Test Password Security",
    description: "Check how strong your password is. Estimate crack time and get improvement tips. Free on ConvertMastery.",
    h1: "Password Strength Checker",
    intro: "Evaluate password strength before you use it. Our checker analyzes length, character diversity, and common patterns—without sending your password to a server.",
    howToUse: ["Type or paste a password.", "Review strength score and feedback.", "Improve weak passwords using suggestions."],
    supportedFormats: "Any password string.",
    privacySecurity: "Analysis runs in your browser. Do not reuse real passwords on untrusted sites; use this tool to test patterns only.",
    useCases: ["Validate new passwords before saving.", "Educate teams on password policy.", "Compare passphrase vs short complex passwords."],
    relatedTools: securityRelated.filter((t) => t.href !== "/password-strength-checker"),
    faqs: [
      { q: "Is my password sent to a server?", a: "No. Checking happens locally in your browser." },
    ],
  },
  "ip-lookup": {
    id: "ip-lookup",
    path: "/ip-lookup",
    title: "IP Address Lookup – Free IP Geolocation Tool",
    description: "Look up IP address location, ISP, and network details. Free IP lookup tool on ConvertMastery.",
    h1: "IP Address Lookup",
    intro: "Find approximate geographic location, ISP, and ASN information for any public IPv4 or IPv6 address. Useful for network troubleshooting and security awareness.",
    howToUse: ["Enter an IP address or use auto-detect for your IP.", "View location, ISP, and network details."],
    supportedFormats: "IPv4 and IPv6 public addresses.",
    privacySecurity: PRIVACY_SERVER_SIDE,
    disclaimer: SECURITY_TOOL_DISCLAIMER,
    useCases: ["Verify login locations.", "Debug CDN and DNS issues.", "Research suspicious traffic sources."],
    relatedTools: [{ href: "/whois-checker", label: "Whois Checker" }, { href: "/website-security-score", label: "Website Security Score" }],
    faqs: [
      { q: "How accurate is IP geolocation?", a: "City-level accuracy is approximate and may not reflect exact physical location." },
    ],
  },
  "whois-checker": {
    id: "whois-checker",
    path: "/whois-checker",
    title: "Whois Lookup – Domain Registration Info",
    description: "Look up domain whois records, registrar, and expiry dates. Free whois checker on ConvertMastery.",
    h1: "Whois Domain Lookup",
    intro: "Query public WHOIS databases for domain registration details including registrar, creation date, nameservers, and status. Essential for domain research and due diligence.",
    howToUse: ["Enter a domain name.", "View registration and nameserver information."],
    supportedFormats: "Domain names (example.com).",
    privacySecurity: PRIVACY_SERVER_SIDE,
    disclaimer: `${SECURITY_TOOL_DISCLAIMER} WHOIS data is public registry information and may be redacted under GDPR privacy services.`,
    useCases: ["Verify domain ownership before purchase.", "Check expiry dates.", "Investigate phishing domains."],
    relatedTools: [{ href: "/ip-lookup", label: "IP Lookup" }, { href: "/website-security-score", label: "Website Security Score" }],
    faqs: [
      { q: "Why is some whois data hidden?", a: "Many registrars offer privacy protection that redacts contact details." },
    ],
  },
  "metadata-remover": {
    id: "metadata-remover",
    path: "/metadata-remover",
    title: "Image Metadata Remover – Strip EXIF Data",
    description: "Remove EXIF metadata from photos online. Strip GPS, camera info, and hidden data. Free on ConvertMastery.",
    h1: "Image Metadata Remover",
    intro: "Photos often contain EXIF metadata including GPS coordinates, camera model, and timestamps. Remove this hidden data before sharing images online.",
    howToUse: ["Upload JPG or PNG images.", "Process to strip metadata.", "Download clean images."],
    supportedFormats: "JPG, PNG, WebP.",
    privacySecurity: PRIVACY_CLIENT_SIDE,
    useCases: ["Share photos without revealing location.", "Publish images on websites without EXIF bloat.", "Protect journalist and activist privacy."],
    relatedTools: [{ href: "/compress", label: "Image Compressor" }, { href: "/convert", label: "Image Converter" }],
    faqs: [
      { q: "What metadata is removed?", a: "EXIF including GPS, camera settings, timestamps, and software tags." },
    ],
  },
  "fake-email-generator": {
    id: "fake-email-generator",
    path: "/fake-email-generator",
    title: "Temporary Email Generator – Disposable Inbox",
    description: "Generate a temporary disposable email address for sign-ups and testing. Free temp email on ConvertMastery.",
    h1: "Temporary Email Generator",
    intro: "Create a short-lived disposable email address to reduce spam in your primary inbox when signing up for trials, downloads, or one-time verifications. Use responsibly and only for legitimate purposes.",
    howToUse: ["Generate a temporary email address.", "Copy and use it for verification.", "Check the inbox for incoming messages."],
    supportedFormats: "Temporary email addresses with live inbox.",
    privacySecurity: "Temporary inboxes are public to anyone with the address. Do not use for sensitive accounts, banking, or confidential communications.",
    disclaimer: `${ADSENSE_DISCLAIMER} Do not use temporary email to bypass bans, commit fraud, harass others, or violate website terms of service. This tool is for legitimate privacy and testing only.`,
    useCases: ["Sign up for free trials without spam.", "Test email verification flows in development.", "Protect your primary email from marketing lists."],
    relatedTools: [{ href: "/email-reputation-checker", label: "Email Reputation Checker" }, { href: "/password-generator", label: "Password Generator" }],
    faqs: [
      { q: "How long does the inbox last?", a: "Temporary addresses expire after a limited period. Use them promptly." },
      { q: "Is it safe for banking?", a: "No. Never use disposable email for financial or critical accounts." },
    ],
  },
  "website-security-score": {
    id: "website-security-score",
    path: "/website-security-score",
    title: "Website Security Score Checker",
    description: "Check website security headers, SSL, and basic security posture. Free security score tool on ConvertMastery.",
    h1: "Website Security Score",
    intro: "Get a quick overview of a website's security configuration including HTTPS, security headers, and common best practices. Results are informational, not a guarantee of safety.",
    howToUse: ["Enter a website URL.", "Review the security score and recommendations."],
    supportedFormats: "Public HTTP/HTTPS URLs.",
    privacySecurity: PRIVACY_SERVER_SIDE,
    disclaimer: SECURITY_TOOL_DISCLAIMER,
    useCases: ["Audit your own site's headers.", "Quick check before entering credentials.", "Learn about security best practices."],
    relatedTools: [{ href: "/whois-checker", label: "Whois Checker" }, { href: "/api-status-checker", label: "API Status Checker" }],
    faqs: [
      { q: "Does a high score mean a site is safe?", a: "No. It reflects configuration checks only. Always use caution with unknown sites." },
    ],
  },
  "email-reputation-checker": {
    id: "email-reputation-checker",
    path: "/email-reputation-checker",
    title: "Email Reputation Checker",
    description: "Check email address validity and reputation signals. Free email checker on ConvertMastery.",
    h1: "Email Reputation Checker",
    intro: "Validate email format and check basic reputation signals before sending campaigns or accepting registrations.",
    howToUse: ["Enter an email address.", "Review validation and reputation indicators."],
    supportedFormats: "Standard email addresses.",
    privacySecurity: PRIVACY_SERVER_SIDE,
    disclaimer: SECURITY_TOOL_DISCLAIMER,
    useCases: ["Validate sign-up emails.", "Reduce bounce rates before campaigns.", "Flag suspicious addresses."],
    relatedTools: [{ href: "/fake-email-generator", label: "Temporary Email" }, { href: "/phone-validator", label: "Phone Validator" }],
    faqs: [],
  },
  "phone-validator": {
    id: "phone-validator",
    path: "/phone-validator",
    title: "Phone Number Validator – Format & Validity Check",
    description: "Validate phone number format and country code. Free phone validator on ConvertMastery.",
    h1: "Phone Number Validator",
    intro: "Check whether a phone number is properly formatted for its country and identify basic validity issues before SMS or call workflows.",
    howToUse: ["Enter a phone number with country code.", "Review format and validity results."],
    supportedFormats: "International phone numbers with country codes.",
    privacySecurity: PRIVACY_SERVER_SIDE,
    useCases: ["Validate checkout phone fields.", "Clean CRM contact data.", "Pre-check numbers before SMS APIs."],
    relatedTools: [{ href: "/email-reputation-checker", label: "Email Reputation Checker" }],
    faqs: [],
  },
  "data-breach-checker": {
    id: "data-breach-checker",
    path: "/data-breach-checker",
    title: "Data Breach Checker – Have I Been Pwned Style",
    description: "Check if an email appears in known data breaches. Free breach checker on ConvertMastery.",
    h1: "Data Breach Checker",
    intro: "Search known public breach databases to see if an email address has appeared in reported data leaks. Use results to rotate passwords and enable two-factor authentication.",
    howToUse: ["Enter an email address you own.", "Review any reported breach matches.", "Change passwords on affected services."],
    supportedFormats: "Email addresses.",
    privacySecurity: "Only check emails you own or have authorization to investigate. Queries may use third-party breach intelligence APIs.",
    disclaimer: `${SECURITY_TOOL_DISCLAIMER} Absence of results does not guarantee an account was never compromised. Breach databases may be incomplete.`,
    useCases: ["Personal security audits.", "Awareness after news of a major breach.", "Encourage password manager adoption."],
    relatedTools: [{ href: "/password-generator", label: "Password Generator" }, { href: "/password-strength-checker", label: "Password Strength Checker" }],
    faqs: [
      { q: "Should I panic if my email appears?", a: "Change passwords on affected sites, enable 2FA, and monitor accounts. Unique passwords limit damage." },
    ],
  },
  "api-status-checker": {
    id: "api-status-checker",
    path: "/api-status-checker",
    title: "API Status Checker – Test Endpoint Health",
    description: "Check if an API endpoint is online and measure response time. Free API status checker on ConvertMastery.",
    h1: "API Status Checker",
    intro: "Quickly test whether a public API URL responds and measure latency. Useful for developers monitoring integrations—only test endpoints you own or have permission to probe.",
    howToUse: ["Enter an API URL.", "Run the check and view status code and response time."],
    supportedFormats: "HTTP/HTTPS URLs.",
    privacySecurity: PRIVACY_SERVER_SIDE,
    disclaimer: `${SECURITY_TOOL_DISCLAIMER} Only check APIs you are authorized to test. Excessive requests may violate terms of service.`,
    useCases: ["Verify deployment health.", "Debug integration outages.", "Document uptime for staging environments."],
    relatedTools: [{ href: "/website-security-score", label: "Website Security Score" }],
    faqs: [],
  },
};
